//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Expense_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public short id { get; set; }
        public string names { get; set; }
        public string expensetype { get; set; }
        public Nullable<short> amount { get; set; }
        public string Department { get; set; }
    }
}
